name: order
jobs:
  - destination_database: MealDash # Athena database
    destination_table: orders # Athena table
    output_location: s3://my-athena-query-results/MealDash/expl/orders/ # S3 path for query results
    query: >
      INSERT INTO MealDash.expl.orders
      SELECT 
        order_id,
        menu_id,
        revenue_id,
        quantity,
        price,
        promotion_id
      FROM MealDash.expl.orders_source
